name=${project.name}
version=${project.version}

parent.groupId=${parentGroup}
parent.artifactId=${parentArtifact}
parent.version=${parentVersion}
parent.type=${parentType}

content.${parentContentArtifactId}=${parentContentVersion}
content.${parentContentArtifactId}.groupId=${parentContentGroupId}
content.${parentContentArtifactId}.namespace=

content.${contentArtifact}=${contentVersion}
content.${contentArtifact}.groupId=${contentGroup}
content.${contentArtifact}.namespace=

spa.artifactId=${frontendArtifact}
spa.groupId=${frontendGroup}
spa.version=${frontendVersion}
spa.type=${frontendType}
spa.includes=${frontendArtifact}-${frontendVersion}

property.pih.config.prompt=Specify PIH config (mexico,mexico-ces-ci)?
property.pih.config.default=mexico,mexico-ces-ci
